FROM golang:1.17 AS builder

ENV USER=appuser
ENV UID=1001

RUN adduser \
--disabled-password \
--gecos "" \
--home /nonexistent \
--shell "/sbin/nologin" \
--no-create-home \
--uid "${UID}" \
"${USER}"

VOLUME /go/src/app
WORKDIR ${GOPATH}/src/app/

COPY . .
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/main


FROM scratch

COPY /static /static
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /go/bin/main /go/bin/main
COPY ./static .

USER appuser:appuser

ENTRYPOINT [ "/go/bin/main" ]