FROM golang:1.17 AS builder

WORKDIR ${GOPATH}/src/mypackage/myapp/

COPY . .
COPY /static /static
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/main

ENTRYPOINT [ "/go/bin/main" ]