apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  labels:
    app.kubernetes.io/name: simple-http-server
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-http-server
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-http-server
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: simple-http-server
          image: celestiv/http-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@pg:5432/postgres
