apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deploy
  labels:
    components: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      components: postgres
  template:
    metadata:
      labels:
        components: postgres
    spec:
      containers:
      - name: short-app
        image: postgres:17
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
        env:
          - name: POSTGRES_DB
            value: demo
          - name: POSTGRES_USER
            value: demo
          - name: POSTGRES_PASSWORD
            value: demo
